Make
Datatamer/tamr-cloud-sdk-python pull request #2
Opened 2024-04-19 16:55 UTC by creynolds15

2024-04-22 15:00 UTC, ErinCompaan commented
Looks reasonable to me.

2024-04-22 17:31 UTC, tparikh requested changes, later dismissed

2024-04-22 17:31 UTC, tparikh commented on .gitignore
> +build/dependencies/*
nit: please add a new line at the end of the file

2024-04-22 17:31 UTC, tparikh commented on Makefile
> +	rm -rf build
nit: please add a new line at the end of the file

2024-04-22 23:34 UTC, tparikh commented on tamr_sdk/jobs/jobs_client.py
> +        return self.stub.CreateJob(request)
nit: please add a new line at the end of the file

2024-04-22 23:34 UTC, tparikh commented on .gitignore
> +.idea/*
nit: please add a new line at the end of the file

2024-04-22 23:35 UTC, tparikh commented on requirements.txt
> +google-api-python-client==2.126.0
nit: please add a new line at the end of the file

2024-04-24 13:59 UTC, rubab2 commented
@creynolds15 Let's add a note/disclaimer in the readme that this is an in-development work-in-progress and not ready for use from outside of Tamr's network.

2024-04-25 19:43 UTC, ErinCompaan approved these changes

2024-04-25 20:30 UTC, merged

2024-05-30 14:09 UTC, tamr-github-integrator commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- `v1.0.0`
- [GitHub release](https://github.com/Datatamer/tamr-cloud-sdk-python/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: